// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type ChatEvent struct {
	Type    ChatEventType `json:"type"`
	ChatID  int64         `json:"chatId"`
	Message *Message      `json:"message"`
	User    *User         `json:"user"`
}

type User struct {
	ID     int64      `json:"id"`
	Status UserStatus `json:"status"`
}

type ChatEventType string

const (
	ChatEventTypeMessagePosted  ChatEventType = "MESSAGE_POSTED"
	ChatEventTypeMessageEdited  ChatEventType = "MESSAGE_EDITED"
	ChatEventTypeMessageDeleted ChatEventType = "MESSAGE_DELETED"
	ChatEventTypeUserTyping     ChatEventType = "USER_TYPING"
)

var AllChatEventType = []ChatEventType{
	ChatEventTypeMessagePosted,
	ChatEventTypeMessageEdited,
	ChatEventTypeMessageDeleted,
	ChatEventTypeUserTyping,
}

func (e ChatEventType) IsValid() bool {
	switch e {
	case ChatEventTypeMessagePosted, ChatEventTypeMessageEdited, ChatEventTypeMessageDeleted, ChatEventTypeUserTyping:
		return true
	}
	return false
}

func (e ChatEventType) String() string {
	return string(e)
}

func (e *ChatEventType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ChatEventType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ChatEventType", str)
	}
	return nil
}

func (e ChatEventType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type UserStatus string

const (
	UserStatusOffline UserStatus = "OFFLINE"
	UserStatusOnline  UserStatus = "ONLINE"
)

var AllUserStatus = []UserStatus{
	UserStatusOffline,
	UserStatusOnline,
}

func (e UserStatus) IsValid() bool {
	switch e {
	case UserStatusOffline, UserStatusOnline:
		return true
	}
	return false
}

func (e UserStatus) String() string {
	return string(e)
}

func (e *UserStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserStatus", str)
	}
	return nil
}

func (e UserStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
